apiVersion: v1
kind: Namespace
metadata:
  name: externalns

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: externalns
spec:
  type: ExternalName
  externalName: external.example.com

